### ISSUE TITLE
Melhorias

### ISSUE THREAD

**Issue by raphaklaus** [aureliojargas/carne-leao-docker#1]
Opa, bom trabalho!

Testei aqui e rolou lindo. Porém, pessoalmente eu sou muito fã de soluções inline. Será que dá pra gente conseguir chegar em algo como:

`make run` (pra rodar)

Isso se traduziria no mkdir, xhost assignment, docker run e xhost unassignment.

O que acha?

**Comment by aureliojargas** [comment]
Boa ideia! Criei um script `run.sh` pra isso. Preferi não usar o `make` pra não ter dependência adicional. Vê lá se era isso o que você tinha em mente.

**Comment by raphaklaus** [comment]
Muito bom! Funcionou perfeito. Só um detalhe, não é necessária a linha `docker-compose build`. Por exemplo eu conseguir rodar perfeitamente omitindo ela.

**Comment by aureliojargas** [comment]
Não entendi. No script `run.sh` não tem essa linha. 🤔 

Se estiver falando da linha `docker-compose up`, ela é a versão simplificada do `docker run` pra quem tem o docker-compose instalado. Senão for isso, me explica :)

**Comment by raphaklaus** [comment]
```
Quero criar e rodar a minha própria imagem, localmente
git clone https://github.com/aureliojargas/carne-leao-docker.git
cd carne-leao-docker

docker-compose build
./run.sh
```

Me refiro a penúltima linha!

**Comment by aureliojargas** [comment]
Ah tá, entendi. Funciona sem aquela linha porque daí nesse caso ele usa a imagem do Docker Hub. E se você já tinha rodando o `docker run` antes, já tinha uma cópia local dessa imagem.

Mas estas instruções do README são pra quem quer construir a própria imagem localmente em vez de usar a do Docker Hub, aí o comando de build é necessário.

Eu vou simplificar estas instruções, está meio confuso mesmo. Valeu pelo feedback!

**Comment by raphaklaus** [comment]
Tranquilo! Obrigado pela ferramenta e a issue acho que pode se dar como encerrada.

**Comment by aureliojargas** [comment]
Beleza, muito obrigado pelas suas considerações, me ajudou a deixar as coisas mais claras :+1:
